name: Build Docker Container
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build amd64 image
        run: docker build -t ghcr.io/felix920506/matrix-responses-bot:latest-amd64 --platform linux/amd64 .

      - name: push amd64 image
        run: docker push ghcr.io/felix920506/matrix-responses-bot:latest-amd64
  
  build-and-publish-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build arm64 image
        run: docker build -t ghcr.io/felix920506/matrix-responses-bot:latest-arm64 --platform linux/arm64 .

      - name: push arm64 image
        run: docker push ghcr.io/felix920506/matrix-responses-bot:latest-arm64
  
  generate-manifest:
    runs-on: ubuntu-latest
    needs: [build-and-publish-arm64, build-and-publish-amd64]
    steps:
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull AMD64 image
        run: docker pull ghcr.io/felix920506/matrix-responses-bot:latest-amd64

      - name: Pull ARM64 image
        run: docker pull ghcr.io/felix920506/matrix-responses-bot:latest-arm64

      - name: Create and push manifest images
        run: |
          docker manifest create ghcr.io/felix920506/matrix-responses-bot:latest \
            ghcr.io/felix920506/matrix-responses-bot:latest-amd64 \
            ghcr.io/felix920506/matrix-responses-bot:latest-arm64
          docker manifest push ghcr.io/felix920506/matrix-responses-bot:latest